### ISSUE TITLE
where is the code ?

### ISSUE THREAD

**Issue by jagernicolas** [BullyWiiPlaza/Universal-Pointer-Searcher-Engine#1]
Hi,
there is only the readme, one commit and one branch only, where is the code ?

**Comment by BullyWiiPlaza** [comment]
The code wasn't open sourced, currently, only binaries are provided:
https://github.com/BullyWiiPlaza/Universal-Pointer-Searcher-Engine/releases

**Comment by jagernicolas** [comment]
thank you
